language: R
sudo: false
cache: packages

env:
  global:
    secure: Jz8t1EhJjg5NT01/Yjv3PBehWDbC6BRmpYt22s41yc1a6aCkqUwBISyWUjHO8wV8/0JcmrVTBmJ7RPBC641lBMo7+ClQMULbQsxifUDZfRDkTkDqe56Ry6fO2MpkgQx7/zjcieISNC/ozOVYVKA7c/OCpFTEnqnRw+7m4VGvgH6E1IirAnRu7WUtM9VrvAYPGywNpzxh1tk4yarh02+s9lumIAHLwLF5xPYzMXtSr8F6Oe+re5fuptJiuWwKeUZQS7/tZEUtBhpRwAkQK+S/TEGLN+ugd36kRdZ34GL2RQQIIVAQEVac/AokdPX4GkR2FB6rrhiW41qd3WPcZRdXfSt+fjxZW+RXTKqJlRwIYSr/Vct9DE0g1VsmjF/c/N/Wj5Doelp3A52Ip7XADSHeFtJSTU2zDEBXfXNIsoXgLrZTeLPacTNE8FT3lWs4TAmkNirvd6PG63vE17CzEritY6slK5nCSgfwOJDmGWdHTswkNBqOZ4tw9lB0UTLiX8Li04XwiutfLv8DKL6vWsdnunGOzVb8G9o3LEfIZ2i8cyKK5Ia4iyl4OcFsVhc9PJ1ncVP2EzaRx0DZcboU/x4A125cK2ExKyJ7vxJ4gXzlZYK0XKfOsny78XelM3kxl1VdAjFdhPm/DBQvhk+RnXTuOCq2rzco4+BnQUYZ1k5KXdc=

before_script:
- PACKAGE=`awk '/^Package\:/ { print $2 }' DESCRIPTION`
- VERSION=`awk '/^Version\:/ { print $2 }' DESCRIPTION`
- PKG_TARBALL=${PACKAGE}_${VERSION}.tar.gz

script:
- R CMD build .
- R CMD check ${PKG_TARBALL} --as-cran --no-manual
- R CMD INSTALL ${PKG_TARBALL}
- Rscript -e "pkgdown::build_site(path = '_site')"

deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master
  local_dir: _site
  github_token: $GITHUB_TOKEN

notifications:
  email: false
  slack:
    secure: cG13GUz4C3szTL//TL/vvq+3jyPPkQWYNauf9V2JkpDkoH1JxGl0nhi/gnX0okMKZX7ojSWsziOjayj6P7TEIasCc6gxx/EmdFvs5VHZMNj0kfb1GN9XSrNvZgB3h5qKvWtos/oiuhONKlcNGLocL0n01jTc2sYo1O0WKNo7FI5N9Ia/9d1DPTMIGJ7cORCyZwIIo6aaoB8QsnHzzFzqPRtgLatiiAPeqgi2aueVghSgxAWRNbOvPBVZJde3/iqhVTKhjD9EFg5Po8Yr9vjP4sWJTmcbHFMITRm1yZaVLkXAHKrsfseksLad6AaZY8TxbOmho2YKNefnYbFuyOkUOLrReM4ZxP6PQOHQN3h9eI/V2sRSZj94nsXDfwEWFdNRVJHlgp0uta1t6Ppdx5wIeSeaM89ntKPRloiZQvSNnrrf4fHPlbdDO1EdHIZTwRmcm9ngoEG7q66/uWo+ROm1yuBi40R3TiTNKqrQWs4YpYJBQkhoakD5BlyurKtKm+jnzSjjnz/U0KOzy4U8Ia6vkPHfrXXY4SJs5VsXZZx5YOWLMb88xZObMdGspRnY59XnRHY28clTnPLxfpMpITY4Z6e6cbZxb+Uki4c1bfgKifO6alHAhqthE01NvQTGBIzndfQQ1XXbHLvK5XSj1y33F5yb7ikPaIRwRSsqnhjwlBQ=

