context("Formula Parsing")

test_that("formula parsing is correct", {
  expect_equal(formula_terms(formula(x ~ foo + bar)), c("foo", "bar"))
  expect_equal(formula_terms(formula(x ~ abc)), "abc")
  expect_equal(formula_terms(formula(x ~ abc*abc)), "abc")
  expect_equal(formula_terms(formula(x ~ abc * abc)), "abc")
  expect_equal(formula_terms(formula(x ~ abc : abc)), "abc")
  expect_equal(formula_terms(formula(x ~ xyz(2))), "2")
  expect_equal(formula_terms(formula(x ~ xyz())), "xyz")
  expect_equal(formula_terms(formula(x ~ I(abc^2))), "abc")
  expect_equal(formula_terms(formula(x ~ I(abc ^ 2))), "abc")
  expect_equal(formula_terms(formula(x ~ I(abc^ 1.5))), "abc")
  expect_equal(formula_terms(formula(x ~ I(abc * def))), "abc")
  expect_equal(formula_terms(formula(x ~ I( abc ^ def ))), "abc")
  expect_equal(formula_terms(formula(x ~ as.factor(arg  ))), "arg")
  expect_equal(formula_terms(formula(x ~ log(arg))), "arg")
  expect_equal(formula_terms(formula(x ~ log(  arg))), "arg")
  expect_equal(formula_terms(formula(x ~ log(arg ))), "arg")
  expect_equal(formula_terms(formula(x ~ log( arg ))), "arg")
  expect_equal(formula_terms(formula(x ~ poly(arg, 2))), "arg")
  expect_equal(formula_terms(formula(x ~ func  (  arg, 2 ,3, 4 , 5  ))), "arg")
})

